browser:
  browser_name: chrome
  headless: true
  attach_screenshot: true
  web_element_timeout: 60
environment:
  int:
    env_name: int
    app_url: https://www.selenium.dev/
    title: Selenium
    active: true

  test:
    env_name: test
    app_url: https://logback.qos.ch/
    title: Logback Home
    active: false